version: '3.7'

services:
  scapy-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    hostname: scapy
    container_name: exp-scapy-server
    image: exp-net-scapy
    tty: true
    stdin_open: true
    volumes:
      - ./server:/scapy/src
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
