version: '3.7'

services:
  scapy-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    hostname: scapy
    container_name: exp-scapy-server
    image: exp-net-scapy
    tty: true
    stdin_open: true
    volumes:
      - ./server:/scapy/src
    ports:
      - "48888:48888"
    network_mode: host
